### ISSUE TITLE
Auto Detect No Longer Works

### ISSUE THREAD

**Issue by rangicus** [Xcelled/mabicommerce#11]
Followed instructions perfectly.

**Comment by Magiobiwan** [comment]
Also having this issue. The offsets and data requests probably changed.

**Comment by Surumon** [comment]
Mabinogi has released a new patch that has addressed what they considered "data miners" which apparently has blacklisted Mabicommerce and Morrighan.  So far Mabinogi thinks Morrighan and Mabicommerce are hacks because it one scans incoming packets from the servers and the other reads the data.  I'm going to try and confirm this, so this might be the issues you're both having.

**Comment by Xcelled** [comment]
Seems to work fine for me. I"m releasing 2.0.5 today, see if that fixes it. If not, we'll have to do some digging. Please reopen this if you get more information.
