### ISSUE TITLE
Autodetect isn't working for me.

### ISSUE THREAD

**Issue by Ahlor** [Xcelled/mabicommerce#4]
I'm able to enter all the item values manually while playing the game, but the autodetect isn't picking that up. I ran the game using MorriOneClick, logged in, opened MabiCommerce, clicked connect, and opened trade with the goblin.

For troubleshooting, I went through my routes for about an hour with connect still going to see if it'd kick in eventually, but nothing happened. I logged out of my character (just in case), closed MabiCommerce, ran it as admin this time, logged back in, traded with the goblin, and I still couldn't get it to autodetect. Downgrading to 2.0.1 and disabling my antivirus didn't seem to help either.

I'm using Windows 7 64-bit, and I don't use any mods with the client. I'm not sure if this'll help at all, but here's a screenshot of my Mabinogi folder. http://i.imgur.com/SBWcOzG.png

**Comment by Xcelled** [comment]
Check the Morrighan icon. Does it turn from white to gold when you press "connect"? If not, please upload morrighan.log for me to look at.

Autodetect won't suddenly start working, so no need to run around for an hour if it's not working.

**Comment by Ahlor** [comment]
It does change.

**Comment by Xcelled** [comment]
If you click the "Settings" button, does it look like this?

![image](https://cloud.githubusercontent.com/assets/5599341/9571938/9e890064-4f74-11e5-96fc-61f3794663b7.png)

**Comment by Ahlor** [comment]
Yeah. Exact values and check boxes.

**Comment by liamrs** [comment]
I just made an account to say that I'm having the same problem, my settings window is the same and my Morrighan "M" does change to golden

**Comment by Xcelled** [comment]
I'm unable to reproduce this - my AutoDetect works fine. Is the version number "2.0.2.0" on the settings window? Could you both upload your Morrighan.log files?

Also, could you tell me the state of your characters? For example:
- Any letters active?
- What transportation methods do you have?
- What post and merchant rating?
- Etc.

**Comment by Ahlor** [comment]
Sure, here it is. http://puu.sh/jVvUV/b099b14673.log
The version number is 2.0.2.0.

Tir Chonail (rating 5), wagon, 147464 ducats, no modifiers, commerce mastery C.

**Comment by Xcelled** [comment]
That all looks normal. Please download [MabiPale](https://github.com/exectails/MabiPale2/releases). Pale works like MabiCommerce:
- Start MorriOneClick
- Open MabiPale
- Press the "Connect" button in MabiPale.
- Verify that stuff shows up as you interact with the game.

See also [Section 2 here](http://mabination.com/threads/84537-Guide-How-To-Packet-Log-Mabinogi).

**Comment by Ahlor** [comment]
This is a little discouraging. :( Nothing seems to be coming up on MabiPale either. It connects, and the Morrighan icon does turn gold, but nothing happens. Every time I launch MabiPale, it gives me 4 error messages like this - http://i.imgur.com/TGNvc7D.png. The other 3 missing plugins are EntityLogger.dll, HexPacketParser.dll, and PacketAnalyzer.dll, and give the same error message.

Really sorry for the hassle, Xcelled.

**Comment by Xcelled** [comment]
The plugin errors are unrelated. For some reason that I can't fathom, your Morrighan isn't forwarding packets like it should. Make sure you have the latest Morrighan. I'll also bring @exectails into this, since he wrote Morrighan.

The double-check list:
- You're running MorriOneClick and MabiCommerce as the same user
- You're running both as admin
- They're on the same computer
- AV is disabled

**Comment by Ahlor** [comment]
I have Morrighan 1.4.5. I am running both as the same user and as admin, both are on my C: drive, and AV is disabled.

**Comment by exectails** [comment]
Well, we don't have a single idea what the problem might be... =|

Since you get that exception about Pale's plugins I would've guessed it's some kind of security problem, but the connection does seem to go through Morrighan according to your log, and since the image lights up, the message passing between the programs seems to be working as well.

We might not be able to solve this without more detailed debug information from Morrighan, that one of us would have to add to Morrighan first.

**Comment by Ahlor** [comment]
Yeah, this isn't really making much sense to me either. Never encountered a problem like this on any piece of software I've installed. Usually there will be one odd quirk that would be obvious to point out and fix, but it's pretty tricky when just about everything is stable.

Hmm, I see. Is there anything I can do on my end to help the process along?

**Comment by Eventide215** [comment]
I am having the same issue with the AutoDetect. It just doesn't seem to work anymore, I know that it used to work for me about a month ago. I have gotten MabiPale2 and all that comes through are packets upon logging in or logging out.

I have everything on the same drive, administrator, Morrighan changes color, all updated, etc. Still nothing happens. I have also made sure that all firewalls, antiviruses, etc are turned off and have an exception just in case.

Morrighan log: http://pastebin.com/4qwBtdGC
PowerPatcher log: http://pastebin.com/AKEq4iCm

MabiPale2:
![screenshot 2015-09-17 17 26 30](https://cloud.githubusercontent.com/assets/14337309/9946452/58374a9e-5d61-11e5-9d00-0848079fbf60.png)

Hopefully some of this can help out and get the issue fixed because I love having MabiCommerce around. Meanwhile I'm going to keep trying to see if I can find what is causing the problem.

**Comment by Xcelled** [comment]
This is bizarre. It ONLY collects login packets? That would seem to indicate some kind of internal issue, @exectails , wouldn't it?

As of yet, we still can't reproduce this issue.

**Comment by exectails** [comment]
Actually, Pale not capturing channel packets would usually indicate that the client somehow connected to the channel directly, without going through Morrighan, which could happen if Morrighan didn't fix the connection information packets. However, in that case the log shouldn't say "Tunneling connection [...]". In any case, those two problems _should_ not be related. I think. Maybe. ~_~

It's really weird, especially that so few people experience these problems. It must be some weird glitch with certain configurations, no? I would totally blame 8 and 10, but most people with this problem are using 7 .__.

**Comment by Xcelled** [comment]
If any of you want to grab TcpView, we could test that. You'll want to use Morrighan and log into a channel. Then, run TcpView and find all the "Client.exe" entries. Take a screenshot and posit it here.

**Comment by Eventide215** [comment]
Here's my screenshot with TcpView. You can see that I have both client and morrighan running, and this is with me connected to a channel currently.

![screenshot 2015-09-17 18 55 22](https://cloud.githubusercontent.com/assets/14337309/9948069/dce01ac6-5d6d-11e5-9b5c-4e511fbe26ab.png)

It's weird that this is happening. I didn't have any issue before when I was using autodetect, but like I said it was about a month ago when I used it last. Even if not using it though, I sitll launch with PowerPatcher using Morrighan.

I do use mods like Abyss, but that shouldn't affect the packets or anything, plus I know it has worked with it before.

Also, yes MabiPale is only collecting the login packets. Even after playing for a little while with it connected.

**Comment by Xcelled** [comment]
That shows that the client is indeed connecting through Morrighan. And since the game works, Morrighan is obviously translating and handling packets correctly... And since Pale shows the login packets, it's obviously connecting to Morrighan properly. Basically, everything is working exactly as it should... except it's not.

Do you remember doing anything in the past month? Installing new software, re-configuring something, etc?

**Comment by Eventide215** [comment]
The only thing I have done that could possibly affect it is installed it onto my SSD since that's where I put all my games, but I have it set so I can run it from there perfectly fine as well as having MabiCommerce and MabiPale there.

I suppose if necessary I could redownload and install it back onto my C drive and see if it fixes or not, but another person has the same issue and it's all on C as well.

It definitely seems odd that everything seems to be connecting and Morrighan is catching at least login, but then it seems it stops there and once connecting to the channel the client connects directly and not through Morrighan. There was a Mabi update since I last used it, could that possibly have affected Morrighan or anything like that?

**Comment by Xcelled** [comment]
C drive shouldn't make any difference. Have you made sure you can run all the DLLs? (Check through the properties pages, if you see anything about "enabling" the dll or similar, click it)

If Morrighan was broken by a mabi update, your game wouldn't work at all, since the packets would get corrupted. Whatever the problem is, it seems to be happening _after_ packets are captured. Would you agree, @exectails ?

**Comment by Eventide215** [comment]
Yeah I didn't think that the drive would matter since the game does work along with Morrighan. I checked through all DLLs and there's nothing about enabling them or anything like that.

I figured if the update broke something then it just wouldn't work, but it's pretty much the only thing I can think of that has changed since it last worked for me.

It still seems like Morrighan just isn't capturing packets after I get logged into a channel. I just had it running for over 2 hours while playing and not a single packet showed up. However, the login and pet information packets (upon login) show up without fail. So it's clearly catching the login server, just nothing after that at all. So if anything, this seems to be Morrighan just not working past login.

The issue started around the start of this month, at least that's when the first post was, and the only thing that has changed on Mabi itself is the start of a few events. Like you said though, if it was a Mabi update the game probably would just not work, unless it just now somehow bypasses Morrighan after login.

I should mention as well that I did notice sometimes when logging in lately the game will freeze up for a while or sometimes go not responding for so long it crashes. Sometimes it recovers though and continues on, and it's only during login at the stage with the secondary password, sometimes after selecting a character. I don't know if this issue could be related, but seeing as MabiPale only catches login packets, it could be related.

**Comment by exectails** [comment]
@Xcelled You are right, it does seem to go through Morrighan, and it does seem to forward the packets to the client/server properly, otherwise you wouldn't be able to play at all, so it must happen afterwards.

But that pretty much only leaves sending the packets to the subscribers via WM_COPY, that's the only other thing that happens. We have to make a debug build, with output from the broadcast method, so we can see what's going on in there.

**Comment by Xcelled** [comment]
@Eventide215 The game freezing at the char select screen has been happening for awhile now. It's caused by pressing "log in" immediately after the engine finishes loading. Give it about 10 seconds and you won't crash.

@exectails can you do that?

**Comment by Eventide215** [comment]
Oh ok, I wasn't sure if I was the only one with that issue or not. It just seems to be slightly related, but then again Mabi never was built great performance wise...

I'll keep an eye out on this and keep trying to see if I can find what is causing the issue it still seems to be only a few people with the issue. I might try to get a few friends to try it out, if they are willing, and see if they have problems or not.

**Comment by cdrttn** [comment]
Getting same issue as Eventide on Win 8. MabiPale log is pretty much the same with only login ops recorded. Mabicommerce isn't able to fill in the info automatically.

**Comment by Xcelled** [comment]
Someone else just reported the same thing on MM. @exectails it's growing. We need to look into this.

**Comment by Eventide215** [comment]
Yeah some of my friends are saying that it doesn't work for them now and they thought it just broke with some kind of Mabi update. The issue seems to definitely be growing and neither Morrighan nor MabiCommerce has changed to cause these issues. The only thing left is that it has to be some kind of Mabi update or change. They did have to update their windows, had issues with their ISP, and things like that. Couldn't that have possibly caused an issue with Morrighan?

I know that if it didn't work then Mabi wouldn't work with Morrighan loaded, but it seems that it works fine for logging in, but the moment you are logged into a channel the client connects directly instead of through Morrighan. I don't see how that would cause Mabi to crash or anything like that, but I'm still new to programming and the like.

**Comment by Xcelled** [comment]
The client connects directly and not through Morrighan? That's different from the TcpView output above. Did something change?

**Comment by Eventide215** [comment]
No, I mean that it seems like once you login that Morrighan just doesn't receive packets. I could be completely wrong, but since it gets all login packets then stops, but Mabi stops working, it seems like the client suddenly directly connects as if Morrighan didn't even exist. Since I noticed this problem I have kept MabiPale running whenever I play and it still only shows login packets and I will have Mabi up for hours at a time.

It's weird though that you and exectails seem to be able to get it to connect perfectly fine. Everyone I have been getting to try it out says the autodetect doesn't work for them either.

**Comment by Xcelled** [comment]
The TcpView output you pasted shows that the client is connected to Morrighan, not the NA server. Notice the connection to localhost on the port that morrighan is also connected to. You should re-verify that this is the case the next time you notice pale not working.

![dce01ac6-5d6d-11e5-9b5c-4e511fbe26ab](https://cloud.githubusercontent.com/assets/5599341/10052376/9359dcb2-61f4-11e5-8047-87eb1b2422ce.png)

**Comment by Eventide215** [comment]
I know that it shows as connecting. I'm saying that Morrighan works as having a local virtual server created, then Mabi's connection is routed through it, then it's sent to the Nexon servers. Doing this lets it read the packets before they are sent and received. This works for the login, but it seems right after you connect to a channel that Morrighan isn't actually processing/reading packets anymore.

Like I said before, the only big Mabi changes that I can see are how they had ISP issues and such. That's pretty much the only change I can see that could possibly have an effect on something like this.

I'll definitely re-verify TcpView and the connections later when I play though just to be sure. I'm thinking this is definitely going to need a debug version much like @exectails said. Just so it's more verbose about what is happening specifically.

**Comment by Xcelled** [comment]
> This works for the login, but it seems right after you connect to a channel that Morrighan isn't actually processing/reading packets anymore.

This has been disproved. Your TcpView screenshot, if you were connected to a channel at the time, shows the client is still routed through Morrighan. If Morrighan wasn't processing packets, your game would simply not work, as nothing would get from the server to you or vice versa. Therefore, since you can connect and play, Morrighan's proxy server component is working fine. Another component of Morrighan, the communication with add-ins like MabiPale, is not working.

For this reason, ISP changes wouldn't be the cause of this issue.

**Comment by Eventide215** [comment]
When I said processing them, I meant that it's not processing them as in reading the packets or letting plugins read it. I know that it would have to actually be sending and receiving the actual packets since like I said, the connection is rerouted. If Morrighan wasn't sending/receiving it just simply wouldn't work at all.

Exectails has already said that it seems to be the WM_COPY, but there isn't a debug currently that shows what is going on for that part.

I doubted that ISP changes and such could affect it, but that's the only big thing that has changed on Mabi that could possibly affect something like this I would think. So the issue has to be computer-based, but we can't really be too sure what is causing it. You an exectails seem to have no problem while it seems people with issues are just growing.

It's also odd that it used to work perfectly fine for me, then I didn't use it for about a month and it suddenly didn't work. The only thing I have changed Mabi wise is reinstalled to a different hard-drive, but doing that I moved everything correctly. I still need to try reinstalling to C: which is where it used to be. I doubt it's an issue, but you never really know until you try.

**Comment by Eventide215** [comment]
Not sure what caused this to change, but this is what TcpView looks like now connected to a channel:

![screenshot 2015-09-23 18 28 50](https://cloud.githubusercontent.com/assets/14337309/10060746/2aee23ea-6221-11e5-8134-91cb6304ec96.png)

There's only one Morrighan connection and it only says listening.

This is what happens on the character selection screen:

![screenshot 2015-09-23 18 32 40](https://cloud.githubusercontent.com/assets/14337309/10060778/7f883710-6221-11e5-9be1-c9781802f00f.png)

Upon logging back in after taking these screenshots (I was logged in and playing for a while then decided to test this out) the connection has changed to this:

![screenshot 2015-09-23 18 38 45](https://cloud.githubusercontent.com/assets/14337309/10060880/5baceba0-6222-11e5-9e12-3878c991ba2d.png)

I'm still only getting login packets on MabiPale as well just to re-verify that.

**Comment by exectails** [comment]
Alright, I have actually found a bug, everybody who gets packets at the character selection, but not in-game, try this: http://puu.sh/koACs/544d12e69b.zip (Morrighan_1.4.6b) and tell us if it works.

Now... I thought someone said they don't get _any_ packets, even at the character selection... but I guess that wasn't here?

**Comment by Ahlor** [comment]
Oh nice, it works now! Thanks for the fix, exectails. :) Hopefully this works for everyone else.

Also, thanks for this awesome app, Xcelled. Now that that bug's out of the way, I really enjoy using it.

**Comment by Eventide215** [comment]
Yep, it's fixed for me as well. Autodetect is working as well as MabiPale catching all packets. Thanks for getting this fixed.

I'm curious though, what exactly was the bug?

@exectails It was Kenshin225 that said he wasn't getting any packets at all, but his issue seems to be fixed now as well.

**Comment by exectails** [comment]
The fix shouldn't fix not getting _any_ packets, but as long as it's working...^^

The fix is a little hard to describe, I added something in Morrighan 1.4.5 to handle an exotic client, while doing so I made a mistake in the decryption of the packets, which somehow caused our programs (Pale and Commerce) to ignore the packets, because they weren't decrypted and looked like garbage data. Even though Pale shouldn't have ignored them even then... We also don't know why we weren't able to reproduce this until earlier this morning, it should've happened to everybody, every time.

Oh well.

**Comment by Eventide215** [comment]
Well he did say that when he tried Pale it was giving errors with DLLs or something of the like, so it's possible it was just not running properly so it wasn't getting any packets at all.

Ah I get it. So basically Morrighan wasn't decrypting packets properly. Making Pale and Commerce see packets as garbage data and ignored it. So packets were passing through, they were just encrypted so everything ignored it.

It is odd though that everyone wasn't having the issue since when it's put this way everyone should be having an issue. So really, in the end it's Xcelled and you that were the odd ones out. :P We were normal for having issues. Lol

At least it's fixed now though and I can get back to doing commerce easily. I can't be bothered to play with numbers...^^;

**Comment by Ahlor** [comment]
That fix wasn't suppose to resolve my issue? Huh, weird.

Xcelled explained that the errors I received from Pale wouldn't be related, so it's still kinda up in the air. This seems to be a fairly complex issue, and would probably require a thorough investigation to know the ins and outs of everything. But I don't think it really matters that much. No need to fix what isn't broke, right? I am kinda interested in knowing more, but I wouldn't want anyone to go out of their way to find out.

**Comment by cdrttn** [comment]
Works fine for me now. Thanks
